server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

#log config
logging:
  level:
    root: Info
    com.david.bankapplication: debug

#spring config
spring:
  jpa:
    showSql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
